### ISSUE TITLE
Problem with the output file

### ISSUE THREAD

**Issue by frogstack** [andrewmed/wordsearch#1]
Hi Andrew,

I was trying to evaluate your solution but there is a problem with the output format. Please make sure each line in the output file is a Result object as described on http://sortable.com/challenge/, i.e.

```
{
  "product_name": String
  "listings": Array[Listing]
}

```

An example line in the output file should look like:

```
{"listings": [{"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Red)"}, {"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio Exilim EX-FC150 10.1MP High Speed Digital Camera with 5x Optical Zoom, CMOS Shift Image Stabilization & 2.7-inch LCD (Red)"}, {"currency": "USD", "price": "249.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Black)"}], "product_name": "Casio_Exilim_EX-FC150"}
```

You can validate the format of your output with the following service:

`curl -XPOST -F file=@/path/to/your/results.txt https://challenge-check.sortable.com/validate`

If you are able to fix this up I'd be happy to take another look at your submission.

Thanks!

Graeme (from sortable.com)

**Comment by andrewmed** [comment]
Hi Graeme
Thats right. it is using standard JSON for output instead of JSON lines.
Other than that it is OK. I will fix it in next few days and get back
Andrew

**Comment by andrewmed** [comment]
followup
here is what I get now:

 {"product_name":"Kodak_EasyShare_M320",
  "listings":
  [{"title":"Kodak EasyShare M320 (Silver) Digital Camera",
    "manufacturer":"Kodak",
    "currency":"USD",
    "price":"63.00"},
   {"title":
    "Kodak EasyShare V1003 10MP Digital Camera with 3x Optical Zoom
(Midnight Black)",
    "manufacturer":"Kodak",
    "currency":"USD",
    "price":"64.95"},
   {"title":"Samsung Digimax S1000 Digital Camera",
    "manufacturer":"Samsung",
    "currency":"USD",
    "price":"199.99"},
   {"title":"Kodak EasyShare M320 (Silver) Digital Camera",
    "manufacturer":"Kodak",
    "currency":"USD",
    "price":"63.99"},
   {"title":
    "Kodak EasyShare M320 9.2MP 3x Optical\/5x Digital Zoom HD Camera
(Green)",
    "manufacturer":"Kodak",
    "currency":"USD",
    "price":"49.95"},
   {"title":
    "Canon PowerShot SD4000IS 10 MP CMOS Digital Camera (Silver) + 16GB
Deluxe Accessory Kit",
    "manufacturer":"Canon",
    "currency":"USD",
    "price":"309.95"}]},

**Comment by frogstack** [comment]
That's still not quite right. A single line in the output file should contain a single JSON object with a product and its listings. A single product result should look like this:

```
{"listings": [{"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Red)"}, {"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio Exilim EX-FC150 10.1MP High Speed Digital Camera with 5x Optical Zoom, CMOS Shift Image Stabilization & 2.7-inch LCD (Red)"}, {"currency": "USD", "price": "249.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Black)"}], "product_name": "Casio_Exilim_EX-FC150"}
```

If you output as a file, you can validate it by running this command: 

`curl -XPOST -F file=@/path/to/your/results.txt https://challenge-check.sortable.com/validate`

**Comment by andrewmed** [comment]
fixed
